/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package glutton;

public class Application {
    public String getGreeting() {
        return "Hello World from Glutton!";
    }

    public static void main(String[] args) {
        System.out.println(new Application().getGreeting());
    }
}
